services:
  chat_nginx:
    image: nginx:latest
    ports:
      - "85:80"
      #- "444:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/code/static
      #- /home/me/self-signed/fullchain.pem:/etc/ssl/certs/fullchain.pem  # SSL certificate
      #- /home/me/self-signed/privkey.pem:/etc/ssl/private/privkey.pem  # SSL key
    depends_on:
      - django

  django:
    container_name: "django-chat-backend"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./chat:/code/chat
      - ./core:/code/core
      - ./staticfiles:/code/static
    env_file: ./.env
    depends_on:
      - chat_redis
      - chat_postgres

  chat_redis:
    image: redis:latest
    ports:
      - "6372:6379"

  chat_postgres:
    image: harbor.kodepress.ir/global/postgres:16.1
    container_name: chat-develop-postgres-db-1
    restart: always
    environment:
      - POSTGRES_USER=devAdmin
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5861:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devAdmin"]
      interval: 10s
      timeout: 5s
      retries: 5


  minio:
    image: harbor.kodepress.ir/global/minio/minio:RELEASE.2025-04-08T15-41-24Z-cpuv1
    container_name: minio_server
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_VOLUMES: /data
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9002
    ports:
      - "9000:9000"  
      - "9002:9001"  # Web console
    volumes:
      - minio_data:/data
      # - ./certs:/root/.minio/certs  # for SSL/TLS if you want
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mc:
    image: harbor.kodepress.ir/global/minio/mc:latest 
    container_name: minio_client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      mc alias set local http://minio:9000 minioadmin minioadmin123 &&
      mc mb -p local/my-bucket &&
      mc admin info local &&
      tail -f /dev/null
      "




volumes:
  postgres_data:
  minio_data:
  #logs_postgres_data:
  #s3-volume:
  #prometheus_data:
  #es_data:

