global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'sentry'
    static_configs:
      - targets: ['sentry:9000']  # Replace with the appropriate target for your services
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']  # Redis metrics
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']