name: Deploy GitHub Page

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: actions/setup-docker@v3

      - name: Build Docker Compose images
        run: docker-compose build

      - name: Deploy GitHub Page
        uses: actions/deploy-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          public_key: ${{ secrets.PUBLIC_KEY }}
