name: Deploy to Docker

on:
  push:
    branches:
#      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
#        tags: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'latest' || github.ref }}
        tags: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' && 'latest' || github.ref }}

    - name: Deploy to Docker environment
      run: |
#        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#        docker pull your-docker-image:latest  # Change this to your Docker image name
#        docker run -d -p 8000:8000 --name your-container-name your-docker-image:latest
         docker
