name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: actions/setup-docker@v3

      - name: Build the Docker Compose images
        run: docker-compose build

      - name: Push the Docker images
        run: docker-compose push
